from datetime import datetime
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
CONTEXT_FILE = ROOT / "GPT_CONTEXT.md"
LATEST_FILE = ROOT / "LATEST.md"
VERSION = "v1.64-dev"
URL = "http://localhost:8502"
CURRENT_BEST_PORTFOLIO = "推荐组合（当前最优）"
CURRENT_UTILITY = "Calculated per selected match"
TOP_ISSUE = "Validate Market Center Score and direction-over-tempo weighting on Brazil vs Haiti and future deep-favorite matches."


def run(command):
    try:
        result = subprocess.run(
            command,
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return ""
    return result.stdout.strip()


def modified_files():
    output = run(["git", "status", "--short", "--untracked-files=all"])
    files = []
    for line in output.splitlines():
        if not line.strip():
            continue
        files.append(line[2:].strip())
    return files or ["None"]


def running_status():
    output = run(["lsof", "-i", ":8502"])
    if "LISTEN" in output:
        return f"Running: {URL}"
    return "Not confirmed"


def bullet(items):
    return "\n".join(f"- {item}" for item in items)


def numbered(items):
    return "\n".join(f"{index}. {item}" for index, item in enumerate(items, start=1))


def build_context():
    updated = datetime.now().strftime("%Y-%m-%d %H:%M")
    modified = modified_files()
    status = running_status()
    content = f"""# WorldCup Analyzer

## Quick Access

Read First:
LATEST.md

Project Context:
GPT_CONTEXT.md

History:
CHANGELOG.md

## Project Status

Version: {VERSION}

Updated: {updated}

Modified Files:
{bullet(modified)}

Status:
{status}

## Current Recommendation

Current Best Portfolio:
- Generated by Odds Distribution Optimizer
- Uses real Match Winner, Asian Handicap, Over/Under, and Correct Score odds when available
- Uses user-entered actual odds when provided

Total Stake:
- Determined by direction confidence and odds value
- Minimum stake is never 0

Current Metrics:
- EV: calculated per selected match
- Sharpe: calculated per selected match
- Stability: calculated per selected match

## Current Model

Enabled:
- Score Probability Distribution
- Full Score State Space
- Return Matrix
- Utility Function
- Kelly
- Sharpe
- Insurance Cost
- Insurance Efficiency
- Correlation Matrix
- Marginal Contribution
- Efficient Frontier
- Portfolio Optimizer
- Odds Distribution Optimizer
- Betting Asset Role Framework
- Multi-Role Asset Allocation
- Role-Driven Portfolio Optimizer
- Pre-Match Decision Cockpit
- Asset Role Contribution
- Match Snapshot
- Prediction Audit
- Recommendation Audit
- Portfolio Style
- Style Performance Database
- My Portfolio
- Post Match Analysis
- Strategy Settlement

## Current Problems

{numbered([
    "Pre-match decision cockpit needs validation against finished matches and saved snapshots.",
    "Score probability distribution still needs calibration against real match results.",
    "Correct score marginal EV depends on bookmaker implied probability and may need de-vig adjustment.",
    "Insurance, return, directional, tempo, and tail role sizing needs more live-match validation.",
    "Some matches still lack full API-Football handicap or correct score coverage.",
    "API data refresh should be executed through terminal scripts first, then saved to cache/history.",
    "Prediction Audit and Recommendation Audit need validation on finished matches.",
    "Portfolio Style statistics need more post-match samples.",
])}

## Current Conclusions

{bullet([
    "Do not use estimated correct score odds.",
    "Use real odds only for Match Winner, Asian Handicap, Over/Under, and Correct Score.",
    "Every betting item can carry multiple weighted asset roles, not just one market type.",
    "Correct Score can carry Return, Directional, Tail, or Insurance roles depending on score path and odds.",
    "Match Winner, Asian Handicap, and Over/Under can carry Insurance, Directional, Tempo, or Return roles depending on context.",
    "Recommended portfolio is generated by the optimizer, not by fixed slots.",
    "Pre-match page now mirrors post-match structure: ranking, role allocation, settlement preview, risk paths, and outcome preview.",
    "Optimizer now adjusts utility based on asset role balance.",
    "Portfolio naming is unified as Recommendation and Alternatives.",
    "Odds data should be cached for at least 24 hours per match.",
    "Match Snapshot is saved under data/history and should not be overwritten.",
    "My Portfolio is saved separately and used for post-match settlement.",
    "Post-match analysis now splits profit and stake across multiple asset roles.",
    "Permanent history lives under data/history and is separate from expiring API cache.",
    "Pre-match snapshots use *_pre.json and post-match snapshots use *_post.json.",
    "API pulls should be verified through terminal scripts before relying on page rendering.",
    "Prediction Audit links pre-match recommendation reasons to post-match outcomes.",
    "Recommendation Audit records which recommendation logic failed or worked.",
    "Portfolio Style classifies strategies as Aggressive, Balanced, or Conservative.",
    "Model Version Tracking is saved into each new pre/post-match snapshot.",
])}

## Next Step

{numbered([
    "Validate Pre-Match Decision Cockpit on finished matches.",
    "Validate multi-role Betting Asset Framework on finished matches.",
    "Validate Post Match Analysis on finished matches.",
    "Validate Prediction Audit on finished matches.",
    "Validate Portfolio Style Performance after more settled matches.",
    "Validate Odds Distribution Optimizer on finished matches.",
    "Calibrate score probability distribution.",
    "Calibrate role balance adjustment thresholds.",
    "Review whether return and tail asset sizing is too aggressive or too conservative.",
])}

## GPT Focus

{numbered([
    "Does the pre-match strategy ranking predict which strategy performs best after the match?",
    "Are multi-role weights correctly assigned for winner, handicap, total, and correct score bets?",
    "Does post-match role contribution correctly explain which asset roles helped or hurt?",
])}
"""
    return compress_context(content)


def build_latest():
    updated = datetime.now().strftime("%Y-%m-%d %H:%M")
    status = "Running" if "Running:" in running_status() else "Stopped"
    return f"""# WorldCup Analyzer

Version: {VERSION}

Updated: {updated}

Status: {status}

Current Best Portfolio: {CURRENT_BEST_PORTFOLIO}

Current Utility: {CURRENT_UTILITY}

Top Issue: {TOP_ISSUE}

GPT Context: GPT_CONTEXT.md

Change Log: CHANGELOG.md
"""


def compress_context(content):
    lines = content.splitlines()
    if len(lines) <= 200:
        return content

    keep_sections = {
        "# WorldCup Analyzer",
        "## Quick Access",
        "## Project Status",
        "## Current Problems",
        "## Current Conclusions",
        "## Next Step",
        "## GPT Focus",
    }
    result = []
    keep = False
    for line in lines:
        if line.startswith("#"):
            keep = line in keep_sections
        if keep:
            result.append(line)
    return "\n".join(result).strip() + "\n"


def main():
    LATEST_FILE.write_text(build_latest(), encoding="utf-8")
    CONTEXT_FILE.write_text(build_context(), encoding="utf-8")
    print(f"Updated {LATEST_FILE}")
    print(f"Updated {CONTEXT_FILE}")


if __name__ == "__main__":
    main()
